New imu
CharlesCossette/pynav pull request #21
Opened 2022-09-24 20:37 UTC by CharlesCossette

Main enhancements include:

- Exact discretization up to assumption of constant IMU measurements in body frame
- `IMUKinematics` class now compatible with both `IMUState` and `SE23State` (for cases where biases are not being estimated)
- Both left and right jacobians now implemented
- Bunch of tests

The `models.py` file was getting massive at 1000+ lines of code. As such, i have created a seperate `imu.py` file for all the IMU related stuff, and also a bunch of stuff has been added to `lib/__init__.py` to simplify the namespace

2022-09-26 12:59 UTC, vkorotkine requested changes
Changes look neat. Comments: 

1. test_imu.py looks like unit tests, recommend adding under tests/unit folder. 
2. Are there integration tests for this? I didn't see any under "tests", not sure if I missed any. Integration tests useful to see exactly to what degree this works, and make it easy to see if anything is quietly bugged.

2022-09-26 14:04 UTC, mitchellcohen3 approved these changes
Looks very slick! I think a bit more documentation or just references to equation numbers in Barfoot's textbook, specifically for the N_matrix and U_matrix could be useful, though these can be done in a future PR

2022-09-26 14:04 UTC, mitchellcohen3 commented on pynav/lib/imu.py
> +        The continuous-time IMU equations are discretized using the assumption
Here this should be changed to: "The continuous-time IMU equations are discretized using the assumption that the IMU measurements are constant between two timesteps".

2022-09-27 21:02 UTC, vkorotkine approved these changes

2022-09-28 12:41 UTC, merged